[tool.cibuildwheel]
build = ["cp37-win32"]
before-all = "make preprocess win32=1"
test-requires = "pytest"
test-command = "python -bb -m pytest {project}/tests/unittest"
test-extras = ["test"]
test-skip = "pp*"
