#!/usr/bin/env bash

CONST_FILE=_const.py
echo "# This file is automatically generated, do not modify directly" > $CONST_FILE
echo "from enum import IntEnum" > $CONST_FILE
echo "class CurlOpt(IntEnum):" >> $CONST_FILE
echo "#include <curl/curl.h>"|gcc -E -|grep -i "CURLOPT_.\+ ="|sed "s/  CURLOPT_/\t/g"|sed "s/,//g" >> $CONST_FILE
# Handling opt renames
cat << EOF >> $CONST_FILE
	if locals().get("WRITEDATA"):
		FILE = locals().get("WRITEDATA")
	if locals().get("READDATA"):
		INFILE = locals().get("READDATA")
	if locals().get("HEADERDATA"):
		WRITEHEADER = locals().get("HEADERDATA")
EOF

echo "" >> $CONST_FILE
echo "" >> $CONST_FILE
echo "class CurlInfo(IntEnum):" >> $CONST_FILE
echo "#include <curl/curl.h>"|gcc -E -|grep -i "CURLINFO_.\+ ="|sed "s/  CURLINFO_/\t/g"|sed "s/,//g" >> $CONST_FILE
# Handling info renames
cat << EOF >> $CONST_FILE
	if locals().get("RESPONSE_CODE"):
		HTTP_CODE = locals().get("RESPONSE_CODE")
EOF
