#!/bin/bash
echo "# This file is automatically generated, do not modify directly" > curl_constants.py
echo "class CurlOpt(object):" >> curl_constants.py
echo "#include <curl/curl.h>"|gcc -E -|grep -i "CURLOPT_.\+ ="|sed "s/  CURLOPT_/\t/g"|sed "s/,//g" >> curl_constants.py
# Handling opt renames
cat << EOF >> curl_constants.py
	if locals().get("WRITEDATA"):
		FILE = locals().get("WRITEDATA")
	if locals().get("READDATA"):
		INFILE = locals().get("READDATA")
	if locals().get("HEADERDATA"):
		WRITEHEADER = locals().get("READDATA")
EOF

echo "" >> curl_constants.py
echo "" >> curl_constants.py
echo "class CurlInfo(object):" >> curl_constants.py
echo "#include <curl/curl.h>"|gcc -E -|grep -i "CURLINFO_.\+ ="|sed "s/  CURLINFO_/\t/g"|sed "s/,//g" >> curl_constants.py
# Handling info renames
cat << EOF >> curl_constants.py
	if locals().get("RESPONSE_CODE"):
		HTTP_CODE = locals().get("RESPONSE_CODE")
EOF